### ISSUE TITLE
Residential sales data no longer available

### ISSUE THREAD

**Issue by StephenFiser** [DataVizToolkit/residential_sales#1]
Hi.

I'm attempting to visit the URLs listed for the Maryland Residential Sales data, and I'm getting a "Not authorized" message.

Any alternative ways to get the data?

Thanks!

**Comment by StephenFiser** [comment]
Scratch that. Found it in you repo.

**Comment by barrettclark** [comment]
I'm glad you found the data and hope you're enjoying the book.

**Comment by owlfox** [comment]
I think the data has been moved to here:
https://data.maryland.gov/Housing/Maryland-Total-Residential-Sales-2012-2015-Zipcode/h3hk-wep2
